# fly.toml app configuration file generated for snowy-smoke-5807 on 2023-06-01T12:38:30-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "snowy-smoke-5807"
primary_region = "mia"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
